* Makefile.in (doc-status): Add hacky target to see what is undocumented... "for maintainer's use only".

diff --git a/neon/trunk/Makefile.in b/neon/trunk/Makefile.in
--- a/neon/trunk/Makefile.in
+++ b/neon/trunk/Makefile.in
@@ -198,3 +198,10 @@ compile-gmo:
 	 echo "> Compiling \"$$f\" catalog:"; \
 	 $(MSGFMT) --statistics -c -o po/$$f.gmo $(top_srcdir)/po/$$f.po; \
 	done
+
+doc-status:
+	@echo -n "Missing docs for:"
+	@for f in `nm src/.libs/libneon.so | grep ' T ' | colrm 1 11`; do \
+	   test -f doc/man/$$f.3 || echo -n " $$f"; \
+	done; echo
+
